"""add source field, chnage external_id to str

Revision ID: 0292e7a7f62b
Revises: 4360d10ab58f
Create Date: 2026-07-21 16:53:18.391982

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0292e7a7f62b"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "4360d10ab58f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vacancies", sa.Column("source", sa.String(), nullable=False))
    op.alter_column(
        "vacancies",
        "external_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("vacancies_external_id_key"), "vacancies", type_="unique")
    op.create_unique_constraint(
        "uq_vacancy_source_external_id", "vacancies", ["source", "external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_vacancy_source_external_id", "vacancies", type_="unique")
    op.create_unique_constraint(
        op.f("vacancies_external_id_key"),
        "vacancies",
        ["external_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "vacancies",
        "external_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="external_id::integer",
    )
    op.drop_column("vacancies", "source")
    # ### end Alembic commands ###
